name: SwiftyApp
options:
  bundleIdPrefix: com.swiftyid
targets:
  SwiftyApp:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - Codes
      - Resources
    scheme:
      testTargets:
        - SwiftyTests
    dependencies:
      - carthage: Alamofire
    settings:
      base:
        INFOPLIST_FILE: Info.plist
  SwiftyTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - Tests
    dependencies:
      - target: SwiftyApp


